# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
  release-ppa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts

      - name: Extract source code
        run: |
          cd $GITHUB_WORKSPACE/artifacts
          mkdir deb-build && cp *.tar.gz deb-build && cd deb-build
          tar xf *.tar.gz
          
      - name: Publish PPA
        uses: yuezk/publish-ppa-package@develop
        with:
          repository: 'ppa:stefanlobbenmeier/hynotix'
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          pkgdir: '${{ github.workspace }}/artifacts/deb-build/globalprotect-openconnect*/'
